export const GROUPME_LOGIN_REQUESTED = "USER_LOGIN_REQUESTED"
export const GROUPME_LOGOUT_REQUESTED = "USER_LOGOUT_REQUESTED"
export const GROUPME_LOGIN_SUCCESS = "GROUPME_LOGIN_SUCCESS"
export const GROUPME_LOGOUT_SUCCESS = "GROUPME_LOGOUT_SUCCESS"

export const GROUPME_API_FAILED = "GROUPME_API_FAILED"

export const GROUPME_GROUPS_REQUESTED = "GROUPME_GROUPS_REQUESTED"
export const GROUPME_GROUPS_SUCCESS = "GROUPME_GROUPS_SUCCESS"
